## Numpy - 3 & Pandas - 1

In [1]:
import numpy as np

In [2]:
a_list = [6,1,2,3]
b_list = [5,7,8,9]
print(a_list + b_list)

[6, 1, 2, 3, 5, 7, 8, 9]


In [ ]:
a = np.array([6,1,2,3])
b = np.array([5,7,8,9])
print(a + b)
print(a*b) ## element wise multiplication

[11  8 10 12]
[30  7 16 27]


#### Vectorization is the ability of the CPU to compute different instructions in parallel

In [5]:
a = np.array([6,1,2,3])
b = np.array([5,7,8,9])

In [6]:
print(np.dot(a,b)) ## np.dot = dot product Eai * bi ==> a1*b1 + a2*b2 + a3*b3

# multiplication  + summation

80


In [45]:
aa = np.array([[1,2,3], [4,5,6]])
bb = np.array([[1,2,3], [4,5,6]])
print(aa.shape)
print(bb.shape)

(2, 3)
(2, 3)


In [46]:
np.dot(aa,bb)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [47]:
np.dot(aa,bb.T) ## T is transpose the shape for the shapes to align

array([[14, 32],
       [32, 77]])

In [50]:
aa@bb.T  ## USE OF THE @ Decorator to perform same operation as np.dot

array([[14, 32],
       [32, 77]])

In [13]:
shop_amazon =np.array ([
    [100,200,20,30,5], ## state1 inventory
    [200,400,40,60,10], ## state2 inventory
])
print(shop_amazon.shape)

(2, 5)


In [14]:
price_amazon = np.array([
    [30,10,1000,10,200], ## state1 price
    [34,12,1100,11,220], ## state2 price
])
print(price_amazon.shape)

(2, 5)


In [16]:
price_amazon.T

array([[  30,   34],
       [  10,   12],
       [1000, 1100],
       [  10,   11],
       [ 200,  220]])

In [17]:
sales = np.dot(shop_amazon, price_amazon.T)

In [18]:
sales

array([[26300, 29230],
       [52600, 58460]])

In [21]:
diag = np.eye(2)
print(diag)

[[1. 0.]
 [0. 1.]]


In [22]:
np.sum(sales*diag)

np.float64(84760.0)

#### Aggregation functions

In [23]:
a2=np.array([1,2,3,4,5])

In [24]:
np.sum(a2)

np.int64(15)

In [25]:
np.max(a2)

np.int64(5)

In [26]:
np.min(a2)

np.int64(1)

In [27]:
a3 = np.array([1,2,400,45,450,2,5])
np.argmax(a3) # it gives us index of the largest number in the array

np.int64(4)

In [28]:
price_amazon = np.array([
    [30,10,1000,10,200], ## state1 price
    [34,12,1100,11,220], ## state2 price
])

In [29]:
np.sum(price_amazon)

np.int64(2627)

In [31]:
np.sum(price_amazon, axis=0) # axis -> 0 means sum over rows and keep the columns

array([  64,   22, 2100,   21,  420])

In [32]:
np.sum(price_amazon, axis=1) # axis -> 0 means sum over columns and keep the rows

array([1250, 1377])

In [33]:
np.mean(a3)

np.float64(129.28571428571428)

In [34]:
np.mean(price_amazon)

np.float64(262.7)

In [36]:
np.mean(price_amazon, axis=1) # average price of all products in state 1, and average price of all products in state 2

array([250. , 275.4])

In [37]:
np.std(price_amazon, axis=1)

array([381.73289091, 419.66539052])

In [38]:
price_amazon2 = np.array([
    [30,10,1000,10,200], ## state1 price
    [34,12,1100,11,220],
    [34,12,1100,11,220] ## state2 price
])

In [ ]:
np.std(price_amazon2, axis=1) ## standard deviation

array([381.73289091, 419.66539052, 419.66539052])

In [41]:
np.cumsum(price_amazon, axis=1) ## cumulative sum

array([[  30,   40, 1040, 1050, 1250],
       [  34,   46, 1146, 1157, 1377]])

In [42]:
a4 = np.array([1,2,400,45,450,2,5])
np.cumsum(a4)

array([  1,   3, 403, 448, 898, 900, 905])

In [43]:
np.cumprod(a4)

array([        1,         2,       800,     36000,  16200000,  32400000,
       162000000])

In [51]:
np.median(price_amazon2, axis=1)

array([30., 34., 34.])

In [52]:
np.var(a4)

np.float64(35365.0612244898)

In [53]:
a5 = np.array([1,2,400,45,450,2,5])
np.percentile(a5, 50)

np.float64(5.0)

### sort, search and Counting functions

In [ ]:
arr = np.array([6,3,8,5,9,7,9,11,22,55,11,6,8,552,0])
print("sorted", np.sort(arr))
print("Arg Sort indices", np.argsort(arr)) ## sort by the index 

sorted [  0   3   5   6   6   7   8   8   9   9  11  11  22  55 552]
Arg Sort indices [14  1  3  0 11  5  2 12  4  6  7 10  8  9 13]


In [ ]:
print("insert 4 position in ", np.searchsorted(np.sort(arr), 4)) ## insert 4 in position 2

insert 4 position in  2


In [59]:
### finding how many unique values

print("Unique element", np.unique(arr))

### finding the count of each elements

print("count of each element", np.bincount(arr)) ## start from min ==0 max 8

Unique element [  0   3   5   6   7   8   9  11  22  55 552]
count of each element [1 0 0 1 0 1 2 1 2 2 0 2 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 

In [62]:
arr4 = np.array([6,3,8,5,9,7,9,11,2,5,11,6,8,12,0,17,11,13,8,6,3])

print("insert 4 position in ", np.searchsorted(np.sort(arr4), 4)) ## insert 4 in position 2
### finding how many unique values

print("Unique element", np.unique(arr4))

### finding the count of each elements

print("count of each element", np.bincount(arr4)) ## start from min ==0 max 8

insert 4 position in  4
Unique element [ 0  2  3  5  6  7  8  9 11 12 13 17]
count of each element [1 0 1 2 0 2 3 1 3 2 0 3 1 1 0 0 0 1]


In [65]:
arr_1d = np.array([1,2, 3,4])
for x in arr_1d:
    print(x)

1
2
3
4


In [63]:
arr_2d = np.array([[1,2], [3,4]])
for x in arr_2d:
    print(x)

[1 2]
[3 4]


In [66]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [68]:
arr_a = np.arange(8).reshape(2,2,2)
arr_a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [69]:
arr_a.ndim

3

In [70]:
for x in np.nditer(arr_a):
    print(x)

0
1
2
3
4
5
6
7


In [71]:
a = np.array([1,2,3,4,5])
b= a
print(id(a))
print(id(b))

2516018904976
2516018904976


In [72]:
bb=a.copy()
print(id(a))
print(id(b))
print(id(bb))

2516018904976
2516018904976
2516019159824


In [73]:
aa = a.view()
print(id(a))
print(id(b))
print(id(bb))
print(id(aa))

2516018904976
2516018904976
2516019159824
2516018904304


In [76]:
## VSTACK ==> stack vertically

a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [77]:
## hstack ===> stack horizontally
print(np.hstack((a,b))) ## 

[1 2 3 4 5 6]


### Numpy char and strings

In [78]:
## np.char.<function_name>()

In [99]:
## np.add()

a= np.array(["hello", "world"])
b= np.array(["_user", "_123456"])
print(np.char.add(a,b))

['hello_user' 'world_123456']


In [100]:
print(np.char.multiply(a,b))

ValueError: Can only multiply by integers

In [84]:
## np.char (lower, upper, capitalize)

a= np.array(["hello", "world"])
print(np.char.upper(a))
print(np.char.lower(a))
print((np.char.capitalize(a)))

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [85]:
## np.char.center()

print(np.char.center(a,11,fillchar="*"))

['***hello***' '***world***']


In [90]:
def password(value):
    #print(value[-1:-4:-1])
    p=np.array([value[-4:]])
    print(p)
    print(np.char.center(p,30,fillchar="*"))

In [91]:
password("mynameisAlfredOwoo")

['Owoo']
['*************Owoo*************']


In [93]:
## np.char.replace()

a= np.array(["data_science", "machine_learning"])
print(np.char.replace(a,"_", "*"))

['data*science' 'machine*learning']


In [94]:
print(np.char.split(a, sep="_"))

[list(['data', 'science']) list(['machine', 'learning'])]


In [95]:
## np.char.find(), / np.char.count()

print(np.char.find(a, "learn"))

[-1  8]


In [97]:
print(np.char.count(a, "a"))
print(np.char.count(a, "data"))

[2 2]
[1 0]


### NUMPY COMPLETED

# PANDAS INTRO 

In [101]:
!pip install pandas

   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------  9.7/9.7 MB 50.5 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 43.5 MB/s  0:00:00

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- --------------

In [102]:
import pandas as pd

In [106]:
import pandas as pd

titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(titanic_dataset_github_url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [107]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q


In [111]:
type(df)

pandas.DataFrame

In [108]:
df[["Name", "Sex"]]

,Name,Sex
0,"Braund, Mr. Owen Harris",male
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female
2,"Heikkinen, Miss. Laina",female
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female
4,"Allen, Mr. William Henry",male
...,...,...
886,"Montvila, Rev. Juozas",male
887,"Graham, Miss. Margaret Edith",female
888,"Johnston, Miss. Catherine Helen ""Carrie""",female
889,"Behr, Mr. Karl Howell",male


In [109]:
df.shape

(891, 12)

In [110]:
dir(df)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'T',
 'Ticket',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '