In [40]:
import time

In [41]:
a = list(range(1000000))
b = list(range(1000000))

start_p = time.perf_counter()
c = [x + y for x, y in zip(a, b)]
end_p = time.perf_counter()
total_p = end_p - start_p
print("Python:", total_p)

Python: 0.05645769997499883


In [42]:
a_np = np.array(a)
b_np = np.array(b)

start_n = time.perf_counter()
c_np = a_np + b_np
end_n = time.perf_counter()
total_n = end_n - start_n
print("NumPy:", total_n)

NumPy: 0.0024160000029951334


In [43]:
print(f"Numpy is faster than python by : {total_p/total_n:.2f}")

Numpy is faster than python by : 23.37


## Numpy - I

##### Python list are:
- Flexible but slow for numerical operations
-  not designed for matrix math or
-  does not support vectorised operation
- are memory inefficient for large numerical data

##### Why use Numpy:
-  faster than pure python for numerical computation
- vertorised operation (no explicit loops)
- broadcasting (operate on arrays of different shape)
-  memory efficient
- comes with powerful linear Algebra random tools etc

##### Use of Numpy:
-  Scientific operations in python

In [2]:
! pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\Alfred\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [8]:
#-m pip install --upgrade pip
import numpy as np


#### Creating Arrays in Numpy
 - 1. np.arrays()

In [9]:
arr_1 =np.array([1,2,3,4,5,6])
print(arr_1)
print(type(arr_1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
arr_2 = np.array([[1,2,3], [5,6,7]])
print(arr_2)
print(type(arr_2))

[[1 2 3]
 [5 6 7]]
<class 'numpy.ndarray'>


In [13]:
arr_3 = np.array([1,2,3, "Hello"])
print(arr_3)
print(type(arr_3))

['1' '2' '3' 'Hello']
<class 'numpy.ndarray'>


In [16]:
print(type(arr_3[2]))

<class 'numpy.str_'>


In [18]:
arr_5 = np.array([1,2,3, "Hello"], dtype=np.float16)
# numpy arrays are in strings when just one of the element is str

ValueError: could not convert string to float: 'Hello'

In [19]:
arr_6 = np.array([1,2,3, "10"], dtype=np.float16)
# arrays can have element with one data type
arr_6

array([ 1.,  2.,  3., 10.], dtype=float16)

In [15]:
arr_4 = np.array([1,2,3], dtype=np.int64)
print(arr_4)
print(type(arr_4))
print(type(arr_4[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [20]:
arr_2[0]

array([1, 2, 3])

In [21]:
type(arr_2[0])

numpy.ndarray

In [ ]:
arr_2[0][2]

np.int64(3)

In [23]:
arr_2[1][2]

np.int64(7)

##### 2. np.arange(start, stop, step)

In [24]:
print(np.arange(1,11,2))

[1 3 5 7 9]


In [25]:
# converting it in to a list
a= np.array(np.arange(1,11,2))
a

array([1, 3, 5, 7, 9])

In [26]:
b= np.arange(1,11,2)

In [27]:
b

array([1, 3, 5, 7, 9])

##### 3. np.linspace(start, stop, num=x)
 -  where x is the number of equally spaced numbers 
  - stop is inclusive

In [28]:
np_linspace = np.linspace(1,100,4)
print(np_linspace)
print(type(np_linspace))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [29]:
np_linspace_1 = np.linspace(1,10,10)
print(np_linspace_1)
print(type(np_linspace_1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [30]:
np_linspace_2 = np.linspace(1,100,100)
print(np_linspace_2)
print(type(np_linspace_2))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]
<class 'numpy.ndarray'>


In [32]:
np_linspace_2 = np.linspace(1,100,1000)
print(np_linspace_2)
print(type(np_linspace_2))

[  1.           1.0990991    1.1981982    1.2972973    1.3963964
   1.4954955    1.59459459   1.69369369   1.79279279   1.89189189
   1.99099099   2.09009009   2.18918919   2.28828829   2.38738739
   2.48648649   2.58558559   2.68468468   2.78378378   2.88288288
   2.98198198   3.08108108   3.18018018   3.27927928   3.37837838
   3.47747748   3.57657658   3.67567568   3.77477477   3.87387387
   3.97297297   4.07207207   4.17117117   4.27027027   4.36936937
   4.46846847   4.56756757   4.66666667   4.76576577   4.86486486
   4.96396396   5.06306306   5.16216216   5.26126126   5.36036036
   5.45945946   5.55855856   5.65765766   5.75675676   5.85585586
   5.95495495   6.05405405   6.15315315   6.25225225   6.35135135
   6.45045045   6.54954955   6.64864865   6.74774775   6.84684685
   6.94594595   7.04504505   7.14414414   7.24324324   7.34234234
   7.44144144   7.54054054   7.63963964   7.73873874   7.83783784
   7.93693694   8.03603604   8.13513514   8.23423423   8.33333333
   8.432432

In [31]:
for num in np.linspace(1,10,10):
    print(num)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


##### 4. np.zeros(shape)
- shape of Matrix

In [33]:
npz = np.zeros(5)
npz

array([0., 0., 0., 0., 0.])

In [35]:
npz1 = np.zeros((5,5))
print(npz1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
npz2 = np.zeros((5,5,5))
print(npz2)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [39]:
npz2.ndim

3

##### 5.  np.ones(shape)
 -  shape of matrix with ones

In [44]:
npo_1 = np.ones((2,3))
print(npo_1)

[[1. 1. 1.]
 [1. 1. 1.]]


##### 6. np.full(shape, fill)

- takes shape and whatever the number you want to use

In [45]:
npo_full = np.full((2,3),10)
print(npo_full)

[[10 10 10]
 [10 10 10]]


##### 7. np.eye(shape)
 - does not exist in 1D you require from 2D and above

In [46]:
np_eye = np.eye(3)
print(np_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
np_eye1 = np.eye(2,3)
print(np_eye1)

[[1. 0. 0.]
 [0. 1. 0.]]


In [48]:
np_eye2 = np.eye(3,2)
print(np_eye2)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [50]:
np_eye3 = np.eye(7,7)
print(np_eye3)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


##### 8. np.empty(shape)
- create a matrix but do not fill with anything
- array without initialisation
 - empty array
 

In [51]:
np_empty=np.empty((2,2),dtype=np.int8)
print(np_empty)

[[1 1]
 [1 1]]


In [52]:
np_empty1=np.empty((2,2),dtype=np.float16)
print(np_empty1)

[[0.    0.   ]
 [0.    1.984]]


In [54]:
start_e = time.perf_counter()
np.empty((5,5), dtype=np.int32)
end_e = time.perf_counter()
total_e = end_e- start_e
print(total_e)

5.8399979025125504e-05


In [56]:
start_e = time.perf_counter()
np.empty((5,5), dtype=np.float16)
end_e = time.perf_counter()
total_e = end_e- start_e
print(total_e)

0.00012369989417493343


##### 9. np.random.rand(shape)
- provides random values between 0 and 1
- ML weights random initialisation

In [59]:
np_Ran = np.random.rand(8)
np_Ran

array([0.9440199 , 0.53787547, 0.8567543 , 0.49037922, 0.1478869 ,
       0.15468577, 0.43797338, 0.51676538])

In [60]:
np_Ran1 = np.random.rand(1,8)
np_Ran1

array([[0.10396945, 0.01800957, 0.95780618, 0.22315258, 0.69842964,
        0.33465386, 0.50467161, 0.37642753]])

In [61]:
np_Ran2 = np.random.rand(2,8)
np_Ran2

array([[0.97458464, 0.48413803, 0.96107189, 0.41298769, 0.90206485,
        0.68332709, 0.94864338, 0.38413267],
       [0.53109088, 0.21428145, 0.87271859, 0.01087687, 0.87216738,
        0.53911091, 0.41219933, 0.22295259]])

In [62]:
np_Ran3 = np.random.rand(4,8)
np_Ran3

array([[0.42952115, 0.13363145, 0.18651867, 0.81881959, 0.41338471,
        0.42352045, 0.59647748, 0.35863942],
       [0.48733194, 0.68695829, 0.74928926, 0.94467435, 0.67227993,
        0.51277967, 0.06821277, 0.86869702],
       [0.71896748, 0.89637195, 0.69028734, 0.30741437, 0.57749693,
        0.16750275, 0.68911881, 0.72704918],
       [0.2194236 , 0.60764678, 0.121382  , 0.51797267, 0.99688045,
        0.47975473, 0.21941017, 0.95496939]])

#### Numpy array attributes (property of a class)

#### 1.ndarray.shape

In [63]:
arr = np.array([[1,2,3,4], [6,7,8,9]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)


2. ndarray.ndim

In [64]:
arr.ndim

2

3. ndarray.size

In [65]:
print(arr.size)

8


4. ndarry.dtype

In [66]:
print(arr.dtype)

int64


5. ndarray.itemsize
 - returns the size of the element

In [67]:
print(arr.itemsize)

8


6. ndarray.nbytes
 - total bytes in array

In [68]:
print(arr.nbytes)

64


7. ndarray.T

Returns the transpose of the array

In [69]:
print(arr)

[[1 2 3 4]
 [6 7 8 9]]


In [70]:
print(arr.T)

[[1 6]
 [2 7]
 [3 8]
 [4 9]]


### Array reshaping and resizing in numpy
1. reshape()
- Total number of elements remains the same
- reshape returns a new view if possible
- use -1 to let numpy infer one dimension

In [71]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)


In [72]:
reshape_1 = arr.reshape(3,2)
print(reshape_1)

[[1 2]
 [3 4]
 [5 6]]


In [73]:
reshape_2 = arr.reshape(1,6)
print(reshape_2)
print(reshape_2.ndim)

[[1 2 3 4 5 6]]
2


In [76]:
arr_w = np.array([1,2,3,4,5,6,10,200,789])
print(arr_w.shape)

(9,)


In [77]:
reshape_3 = arr_w.reshape(3,-1)
print(reshape_3)
print(reshape_3.ndim)

[[  1   2   3]
 [  4   5   6]
 [ 10 200 789]]
2


In [78]:
reshape_3 = arr_w.reshape(4,-1)
print(reshape_3)
print(reshape_3.ndim)

ValueError: cannot reshape array of size 9 into shape (4,newaxis)