## Numpy II

### Array reshaping and resizing in numpy
1. reshape()
- Total number of elements remains the same
- reshape returns a new view if possible
- use -1 to let numpy infer one dimension

### 2. Ravel 
- Changes/flattens multidimensional dataset arrays (matrices) into 1 dimensional dataset.
- returns a view
- a view is a different ndarray object that looks at the same block of memory where the actual numerical values are stored.

In [4]:
import numpy as np

In [13]:
a= np.array([[1,2,3], [4,5,6]])
print(a)
print(a.shape)
a_ravel = a.ravel()
print(a_ravel)
print(a_ravel.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]
(6,)


In [15]:
print(id(a))
print(id(a.ravel()))

2867809728432
2867809720464


In [22]:
## .__array_interface__ ['data'][0]
# attributes point to actual memory  address wgere the raw array data begins

In [18]:
print(f"data address of a : {a.__array_interface__ ['data'][0]}")

data address of a : 2867304212384


In [19]:
print(f"data address of a.ravel directly: {a.ravel().__array_interface__ ['data'][0]}")

data address of a.ravel directly: 2867304212384


In [20]:
a[0][0]=11

In [21]:
a

array([[11,  2,  3],
       [ 4,  5,  6]])

In [23]:
print(f"data address of a : {a.__array_interface__ ['data'][0]}")

data address of a : 2867304212384


In [24]:
print(a_ravel)

[11  2  3  4  5  6]


### 3. Flatten()
- flattens into 1D (returns a copy)

In [25]:
a

array([[11,  2,  3],
       [ 4,  5,  6]])

In [28]:
b= a.flatten()

In [29]:
print(id(a.flatten))
print(id(b.flatten))

2867809859712
2867774472736


In [30]:
print(f"data address of a : {a.__array_interface__ ['data'][0]}")
print(f"data address of a : {b.__array_interface__ ['data'][0]}")

data address of a : 2867304212384
data address of a : 2867294932896


### 4. resize ()

resize array in-place
unlike reshapre(). it can change the total size data may be truncated or padded with zeros

In [32]:
c= np.array([[1,2,3], [4,5,6]])


In [33]:
c.resize((3,3), refcheck=False)

In [34]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [ ]:
c.resize((2,2), refcheck=False) ## In-place: changing the data without reassignment

In [36]:
c

array([[1, 2],
       [3, 4]])

### 5. Squeeze()
- Used to remove single dimensional axes
- used for removing extra dimensions from the image or model output 


In [41]:
d= np.array([[[1]], [[2]],[[3]]])
d

array([[[1]],

       [[2]],

       [[3]]])

In [43]:
d.shape

(3, 1, 1)

In [44]:
e = np.squeeze(d)
e

array([1, 2, 3])

In [45]:
e.shape

(3,)

## Indexing and Slicing in Numpy -- Beginner to Advanced

##### Slicing sytax : array [ start: stop: step]
### 1. indexing in 1D

In [46]:
arr = np.array([10,20,30,40,50])

In [47]:
print(arr[0])

10


In [48]:
print(arr[1])

20


In [49]:
print(arr[-1])

50


In [50]:
print(arr[4])

50


#### array[strt:stop(exclusive): step]
#### arr1 = np.array([10,20,30,40,50])


In [51]:
print(arr[1:4])

[20 30 40]


In [52]:
print(arr[2:4])

[30 40]


In [53]:
print(arr[0:3])

[10 20 30]


In [54]:
print(arr[:3])

[10 20 30]


In [ ]:
### to get this results [10,30,50]
print(arr[0:5:2])

[10 30 50]


In [56]:
print(arr[::-1])  ### reversing

[50 40 30 20 10]


#### Indexing in 2D

##### MAT[ROWS, columns]

In [72]:
MAT  = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [73]:
MAT[0,1]
## MAT[rows, columns]

np.int64(2)

In [74]:
MAT[:,2]

array([3, 6, 9])

In [75]:
MAT[0:2, 1:]

array([[2, 3],
       [5, 6]])

In [76]:
MAT[::-1, ::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

#### 3. Boolean Indexing

In [77]:
arrd = np.array([5,10,15,20,25])

In [78]:
## get elements greater than 15

In [79]:
l=[]

for i in arrd:
    if i> 15:
        l.append(i)
l=np.array(l)
print(l)

[20 25]


In [80]:
arrd[arrd>15]

array([20, 25])

#### 4. Fancy Indexing

In [81]:
arre = np.array([5,10,15,20,25,30,40,45])
indices = [0,2,4]
print(arre[indices])


[ 5 15 25]


In [82]:
mat  = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [83]:
mat[(0,1),(2,2)]

array([3, 6])

In [84]:
mat[mat>5]

array([6, 7, 8, 9])

In [ ]:
mat[[0,1],
    [2,2]]
#    ^,^
## ---> reads it like 0,2 = 3
## ---> reads it like 1,2 = 6

array([3, 6])

#### 5. Modifying with Indexing

In [87]:
arra = np.array([1,2,3,4,5,6])
arra[2]=10
print(arra)

[ 1  2 10  4  5  6]


In [88]:
arra[arra> 2 ]= 100

In [89]:
arra

array([  1,   2, 100, 100, 100, 100])

##### 6. Indexing with np.where()

In [91]:
arrf = np.array([1,2,3,4,5,6,10,50,25,30,45,22])
idx = np.where(arrf > 20)
idx ## this returns the index of the numbers greater then 20

(array([ 7,  8,  9, 10, 11]),)

In [92]:
print(arrf[idx])

[50 25 30 45 22]
